#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

1. Contrapositive

2. Converse
Flipping the hypothesis and the conclusion: 
EX: If it's raining, the weather rock will be wet. VS If the weather rock is wet, then it must be raining.
p -> q VS q -> p
Create a logical statement, then give it's converse statement:

3. inverse

4. R: real numbers

5. Z: integers
Any whole number (no decimals) including negative numbers.
EX: -2, -1, 0, 1, 2 etc.
Which of the follwing is an integer
a) 3i
b) 3.14
c) 7
d) "x"

6. Q: rational numbers

7. predicate

8. Domain
The values that go into a function
EX: 1, 2, 5, 7
What is the domain of the Factorial function if given the values {3, 5, 9, 2}
a) 0
b) 4
c) {3, 5, 9, 2}
d) I don't know

9. CoDomain

10. quantifier

11. antecedent
The first part of a logical statement.
EX: *If the grass is green* then it is summer.
Give the antecedent of the following statement:
If X is a man, X is mortal
A:

12. consequent

13. Set

14. Fallacy
A flaw in reasoning.
EX: There is a teapot orbiting the Earth at this very moment. You can't prove me wrong, so therefore my claim is valid.
What is the fallacy in the following statement:
Red had come up six times in a row on the roulette wheel, so Greg knew that it was close to certain that black would be next up.
A:

15. biconditional

16. sufficient condition

17. necessary condition
A nesessary condition is a condition that must be fulfilled for the outcome to be true or valid.
EX: You must have keys to drive a car.
What would be a necessary condition to fly a plane?
a) You must have own a plane.
b) You must join the airforce.
c) You must have a pilot's licence.
d) You must be able to fly a kite.

18. ~p

19. p ^ q

20. p V q
The result is true if either P is true OR Q is true, or they are both true.
EX: In order to get an icecream cone, you must have at least $1.00 or have a free coupon.
Which of these statements is false?

21. p XOR q

22. p == q

23. p -> q
Statemet P implies statement Q
EX: 

24. p <--> q

25. Three dots in a triangle

26. upside down A
∀ For all items in a set.


27. Backwards E

28. union

29. intersection
The set of values that two sets have in common.
EX: The middle part of a Venn Diagram.
Q:


30. Commutative laws

31. associative laws

32. distributive laws
Similar to the distributive laws in algebra. A variable outside of parenthesis can be distributed to each
term inside the parenthesis to get a correct result.
EX: p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r)


33. identity laws

34. negation laws

35. double negative law
A law that states that if a statement is negated twice, it is equivilant to it's original state.
EX:If a statement is true, then it is not the case that the statement is not true
Q: Which of the following is true:
a) This statement is false.
b) This is not the answer.
c) This statement is not the incorrect answer. 


36. idempotent laws

37. universal bound laws

38. De morgan's laws
A set of rules that define how logical statements can be manipulated.
EX: ~(P ^ Q) -> (~P v ~Q)
Q:


39. absorption laws

40. negations of t and c

41. vacuously true
A truth about an empty set.
EX: All the chairs in the room are orange. (When there are no chairs in the room)
Which of the following is a vacuous truth?
a) This text is black
b) Blueberries are blue.
c) I've never lost a fair game. Never played one.


42. Modus Ponens

43. Modus Tollens

44. Elimination: valid argument form
A rule of inferance that allows us to remove a redundant statement from a logical proof.
EX: If I'm inside, then I have my wallet.
    If I'm outside, then I have my wallet.
    I am either inside or outside, so therefore, I have my wallet on me.
Q: 


45. Transitivity: Valid Argument form
