#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

1. Contrapositive

2. Converse

3. inverse

4. R: real numbers

5. Z: integers

6. Q: rational numbers

7. predicate

8. Domain

9. CoDomain

10. quantifier

11. antecedent

12. consequent

13. Set

14. Fallacy

15. biconditional

16. sufficient condition

17. necessary condition

18. ~p

19. p ^ q

20. p V q

21. p XOR q

22. p == q

23. p -> q

24. p <--> q

25. Three dots in a triangle

26. upside down A

27. Backwards E

28. union

29. intersection

30. Commutative laws

31. associative laws

32. distributive laws

33. identity laws

34. negation laws

35. double negative law

36. idempotent laws

37. universal bound laws

38. De morgan's laws

39. absorption laws

40. negations of t and c

41. vacuously true

42. Modus Ponens

43. Modus Tollens

44. Elimination: valid argument form

45. Transitivity: Valid Argument form
