#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

<<<<<<< HEAD
ANSWER - c

1. Contrapositive

2. Converse

3. inverse - negate antecedent and conclusion of a conditional. Example - s = p \rightarrow q, inverse of s = \not p \rightarrow \not q

4. R: real numbers

5. Z: integers

6. Q: rational numbers - the set of all numbers that can be expressed as a fraction of two integers.

7. predicate

8. Domain

9. CoDomain - For every x in the domain of f, the codomain contains all - and only - the numbers y = f(x)

10. quantifier

11. antecedent

12. consequent - second part of a conditional

13. Set

14. Fallacy

15. biconditional - p if and only if q

16. sufficient condition

17. necessary condition

<<<<<<< HEAD
18. ~p - negation of p. ~0 = 1, ~1 = 0

19. p ^ q

20. p V q

21. p XOR q - exclusive or. returns 1 iff p != q

22. p == q

23. p -> q

24. p <--> q - biconditional. Returns 1 iff p == q

25. Three dots in a triangle

26. upside down A

27. Backwards E - existential quantifier. "There exists" or "there is at least one"

28. union

29. intersection

30. Commutative laws - you can change the order of arguments for certain functions, and the output is the same. 
Example: p \wedge q == q \wedge p

31. associative laws

32. distributive laws

33. identity laws - states that x == x, a == a, etc.

34. negation laws

35. double negative law

36. idempotent laws - a \wedge a == a; a \vee a == a

37. universal bound laws

38. De morgan's laws

39. absorption laws - a \wedge (a \vee b) == a; a \vee (a \wedge b) == a

40. negations of t and c

41. vacuously true

42. Modus Ponens - method of affirming. Allows you to construct arguments from statements.

43. Modus Tollens

44. Elimination: valid argument form

45. Transitivity: Valid Argument form

A \rightarrow B
B \rightarrow C
A == 1
Therefore, 
C == 1
